language: node_js
node_js: stable
install:
  - npm install --force

jobs:
  include:
    - stage: tests
      node_js: stable
      script:
        - npm run test
    - stage: semantic release
      if: branch = master AND type = push
      node_js: stable
      script:
        - npm run release
        - npm run semantic-release
