os:
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '11'
  - '10'
dist: xenial
sudo: required
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
before_install:
  - sudo dpkg --add-architecture i386
  - wget -q -O - https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt-get update
  - sudo apt-get install --install-recommends winehq-stable -y --allow-unauthenticated
install:
  - npm set progress=false
  - npm install

jobs:
  include:
    - stage: tests
      node_js: stable
      script:
        - npm run test
    - stage: semantic release
      if: branch = master AND type = push
      node_js: stable
      script:
        - npm run release
        - npm run semantic-release
